FROM node:18-alpine AS base

FROM base AS deps
WORKDIR /
RUN npm install --global corepack@latest
RUN corepack use pnpm@10.14.0

# Install dependencies using pnpm
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN \
  if [ -f pnpm-lock.yaml ]; then pnpm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

WORKDIR /
COPY --from=deps node_modules ./node_modules
COPY . .

RUN apk add --update --no-cache

CMD ["node", "bin/www"]
