services:
  backend-dev:
    container_name: backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "8083:8082"
    networks:
      - shared_network
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/Documents/Mangas/covers:/public

networks:
  shared_network:
    external: true